# Controlador da garra PG70 (ajuste os nomes das juntas conforme necessário)
# Configuração dos controloladores da garra PG70 no gazebo

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - pg70_finger_left_joint
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.01
    pg70_finger_left_joint: {trajectory: 0.01, goal: 0.01}
  stop_trajectory_duration: 0.2
  state_publish_rate: 50
  action_monitor_rate: 10
