# Controlador da garra PG70 (ajuste os nomes das juntas conforme necessário)
gripper_controller:
  type: position_controllers/JointPositionController
  joint: pg70_finger_left_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}