ur10:
  #Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  #Position controllers and PID
  shoulder_pan_joint_state_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_pan_joint
    pid: {p: 20000,  d: 500, i: 10, i_clamp: 1}

  shoulder_lift_joint_joint_state_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_lift_joint
    pid: {p: 20000,  d: 500, i: 10, i_clamp: 1}

  elbow_joint_state_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 20000,  d: 500, i: 10, i_clamp: 1}

  wrist_1_joint_state_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_1_joint
    pid: {p: 500,  d: 10, i: 1, i_clamp: 1}

  wrist_2_joint_state_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_2_joint
    pid: {p: 500,  d: 10, i: 1, i_clamp: 1}

  wrist_3_joint_state_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_3_joint
    pid: {p: 10,  d: 0.1, i: 0, i_clamp: 1}

  gripper_controller:
    type: effort_controllers/JointPositionController
    joint: pg70_finger_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}


  

