controller_list:
  - name: "/ur10/eff_joint_traj_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  - name: "/ur10/gripper_controller"
    type: position_controllers/JointPositionController
    joint: pg70_finger_left_joint